version: '2'

services:

  slim:
    image: comicrelief/php7-slim:latest
    volumes:
      - .:/var/www/html
    ports:
      - "9001:80"
    depends_on:
      - mysql
    environment:
      APPLICATION_ENV: local

  mysql:
    image: mysql:5.7.17
    volumes:
      - ./.data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: firstblog

